services:
  frontend:
    image: om-frontend:0.0.0
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - 3000:80

  backend:
    image: om-backend:0.0.0
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - 8000:8000
    environment:
      HOST: 0.0.0.0
      WORKERS: 1

  tileserver:
    image: maptiler/tileserver-gl:v5.4.0
    ports:
      - 8080:8080
    volumes:
      - ./tileserver:/data
